name: fbx
version: 0.1.0
description: An opensource decoder for the FBX 3d geometry and animation format.
author: Brendan Duncan <brendanduncan@gmail.com>
homepage: https://github.com/brendan-duncan/dart_fbx
environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'
dependencies:
  archive: '>= 2.0.0 <3.0.0'
  vector_math: '>= 2.0.8 <3.0.0'
dev_dependencies:
  test: '>=0.12.42 <2.0.0'
  pedantic: ^1.0.0
  build_web_compilers: '>=0.3.6 <2.0.0'
  build_runner: '>=1.3.0 <2.0.0'
